version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"

  #added comment
